# -*- coding: utf-8 -*-
"""AML_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mm6iHjTx_wQ3pffqKCgy6HLLWBDa6cgp

#PHASE 1: Dataset Loading & Exploration


> MEMBER : shahad
"""

from google.colab import drive
drive.mount('/content/drive')

# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset
df = pd.read_csv('RTA Dataset.csv')
df.head()

# Dataset shape
print("Dataset Shape:", df.shape)

# Dataset information
df.info()

# Display columns
df.columns

# Summary statistics
df.describe(include='all')

# Target distribution
df['Accident_severity'].value_counts()

# Visualization

plt.figure(figsize=(6,4))
sns.countplot(x='Accident_severity', data=df)
plt.title('Accident Severity Distribution')
plt.xlabel('Accident Severity')
plt.ylabel('Count')

plt.show()

# Missing values
df.isnull().sum()

df.isnull().sum().sum()

"""#PHASE 2: Data Preprocessing


> MEMBER : Razan Adil


"""

# Check for missing values
df.isnull().sum()

# Fill missing values with the most frequent value in each column
df.fillna(df.mode().iloc[0], inplace=True)
# Check if there are still missing values
df.isnull().sum()

from sklearn.preprocessing import LabelEncoder

# Create a label encoder
le = LabelEncoder()

# Apply label encoding to each column with text data
for col in df.columns:
    if df[col].dtype == 'object':  # Only apply to columns with text data
        df[col] = le.fit_transform(df[col])

# Split the data into features (X) and target (y)
X = df.drop('Accident_severity', axis=1)  # Drop the target column
y = df['Accident_severity']  # Target column (Accident severity)

from sklearn.preprocessing import StandardScaler

# Create a scaler
scaler = StandardScaler()

# Apply scaling to the features
X_scaled = scaler.fit_transform(X)
print("Scaled features:", X_scaled[:3])

from sklearn.model_selection import train_test_split

# Split the data into training and testing sets (70% train, 30% test)
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.30, random_state=42, stratify=y)
print("Training set size:", X_train.shape)
print("Testing set size:", X_test.shape)

"""#PHASE 3: MODEL DEVELOPMENT

> MEMBER: Wajd Khalid

#Logistic Regression Model
"""

from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from imblearn.over_sampling import SMOTE
import matplotlib.pyplot as plt
import seaborn as sns


scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


smote = SMOTE(random_state=42)

X_train_resampled, y_train_resampled = smote.fit_resample(
    X_train_scaled,
    y_train
)


model_lr = LogisticRegression(max_iter=1000, random_state=42)

model_lr.fit(X_train_resampled, y_train_resampled)


y_pred_lr = model_lr.predict(X_test_scaled)


lr_accuracy = accuracy_score(y_test, y_pred_lr)

print("Logistic Regression Accuracy:", lr_accuracy)


print("\nLogistic Regression Classification Report:")
print(classification_report(y_test, y_pred_lr))


cm_lr = confusion_matrix(y_test, y_pred_lr)

class_names = ['Slight Injury', 'Serious Injury', 'Fatal Injury']

plt.figure(figsize=(7,5))

sns.heatmap(
    cm_lr,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=class_names,
    yticklabels=class_names
)

plt.title('Confusion Matrix - Logistic Regression')
plt.xlabel('Predicted')
plt.ylabel('Actual')

plt.show()




feature_names = ['Age_band_of_driver', 'Sex_of_driver', 'Driving_experience']


smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X[['Age_band_of_driver', 'Sex_of_driver', 'Driving_experience']], y)


model_lr = LogisticRegression(max_iter=1000, random_state=42)
model_lr.fit(X_resampled, y_resampled)


importance_lr = np.abs(model_lr.coef_[0])


plt.figure(figsize=(10, 6))
plt.barh(feature_names, importance_lr, color='blue')
plt.xlabel('Importance')
plt.title('Feature Importance - Logistic Regression')
plt.show()

"""#Random Forest Model"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from imblearn.over_sampling import SMOTE
import matplotlib.pyplot as plt
import seaborn as sns


smote = SMOTE(random_state=42)

X_train_resampled, y_train_resampled = smote.fit_resample(
    X_train,
    y_train
)

model_rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model_rf.fit(X_train_resampled, y_train_resampled)


y_pred_rf = model_rf.predict(X_test)


rf_accuracy = accuracy_score(y_test, y_pred_rf)

print("Random Forest Accuracy:", rf_accuracy)


print("\nRandom Forest Classification Report:")
print(classification_report(y_test, y_pred_rf))


cm_rf = confusion_matrix(y_test, y_pred_rf)

class_names = ['Slight Injury', 'Serious Injury', 'Fatal Injury']

plt.figure(figsize=(7,5))

sns.heatmap(
    cm_rf,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=class_names,
    yticklabels=class_names
)

plt.title('Confusion Matrix - Random Forest')
plt.xlabel('Predicted')
plt.ylabel('Actual')

plt.show()

feature_importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': model_rf.feature_importances_
})

feature_importance = feature_importance.sort_values(
    by='Importance',
    ascending=False
)

plt.figure(figsize=(10,6))

sns.barplot(
    x='Importance',
    y='Feature',
    data=feature_importance.head(10)
)

plt.title('Feature Importance - Random Forest')

plt.show()

"""#SVM Model"""

from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from imblearn.over_sampling import SMOTE
import matplotlib.pyplot as plt
import seaborn as sns


smote = SMOTE(random_state=42)

X_train_resampled, y_train_resampled = smote.fit_resample(
    X_train_scaled,
    y_train
)


model_svm = SVC(kernel='rbf', random_state=42)

model_svm.fit(X_train_resampled, y_train_resampled)


y_pred_svm = model_svm.predict(X_test_scaled)


svm_accuracy = accuracy_score(y_test, y_pred_svm)

print("SVM Accuracy:", svm_accuracy)


print("\nSVM Classification Report:")
print(classification_report(y_test, y_pred_svm))


cm_svm = confusion_matrix(y_test, y_pred_svm)

class_names = ['Slight Injury', 'Serious Injury', 'Fatal Injury']

plt.figure(figsize=(7,5))

sns.heatmap(
    cm_svm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=class_names,
    yticklabels=class_names
)

plt.title('Confusion Matrix - SVM')
plt.xlabel('Predicted')
plt.ylabel('Actual')

plt.show()

# ===============================
# SVM Decision Boundary
# ===============================

import numpy as np
from matplotlib.colors import ListedColormap

# Use only two features for visualization
X_vis = df[['Number_of_vehicles_involved',
            'Number_of_casualties']].values

y_vis = df['Accident_severity'].values

# Scale the selected features
from sklearn.preprocessing import StandardScaler

sc_vis = StandardScaler()

X_vis = sc_vis.fit_transform(X_vis)

# Split data
from sklearn.model_selection import train_test_split

X_train_vis, X_test_vis, y_train_vis, y_test_vis = train_test_split(
    X_vis,
    y_vis,
    test_size=0.3,
    random_state=42
)

# Train SVM on selected features
svm_vis = SVC(kernel='rbf', random_state=42)

svm_vis.fit(X_train_vis, y_train_vis)

# Create meshgrid
X1, X2 = np.meshgrid(
    np.arange(start=X_test_vis[:, 0].min() - 1,
              stop=X_test_vis[:, 0].max() + 1,
              step=0.01),

    np.arange(start=X_test_vis[:, 1].min() - 1,
              stop=X_test_vis[:, 1].max() + 1,
              step=0.01)
)

# Predict each point in the grid
Z = svm_vis.predict(
    np.array([X1.ravel(), X2.ravel()]).T
)

Z = Z.reshape(X1.shape)

# Plot decision boundary
plt.figure(figsize=(8,6))

plt.contourf(
    X1,
    X2,
    Z,
    alpha=0.5,
    cmap=ListedColormap(('red', 'green', 'blue'))
)

# Plot actual points
for i, j in enumerate(np.unique(y_test_vis)):
    plt.scatter(
        X_test_vis[y_test_vis == j, 0],
        X_test_vis[y_test_vis == j, 1],
        c=ListedColormap(('red', 'green', 'blue'))(i),
        label=j
    )

plt.title('SVM Visualization of Road Traffic Accident Severity')
plt.xlabel('Number of Vehicles Involved')
plt.ylabel('Number of Casualties')

plt.legend()

plt.show()

"""#XGBOOST Model






"""

import xgboost as xgb
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from imblearn.over_sampling import SMOTE
import seaborn as sns
import matplotlib.pyplot as plt


smote = SMOTE(random_state=42)

X_train_resampled, y_train_resampled = smote.fit_resample(
    X_train,
    y_train
)


model_xgb = xgb.XGBClassifier(
    random_state=42,
    eval_metric='mlogloss'
)

model_xgb.fit(X_train_resampled, y_train_resampled)


y_pred_xgb = model_xgb.predict(X_test)


xgb_accuracy = accuracy_score(y_test, y_pred_xgb)
print("XGBoost Accuracy:", xgb_accuracy)


print("\nXGBoost Classification Report:")
print(classification_report(y_test, y_pred_xgb))


cm_xgb = confusion_matrix(y_test, y_pred_xgb)

class_names = ['Slight Injury', 'Serious Injury', 'Fatal Injury']

plt.figure(figsize=(7,5))
sns.heatmap(
    cm_xgb,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=class_names,
    yticklabels=class_names
)

plt.title('Confusion Matrix - XGBoost')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show()

feature_importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': model_xgb.feature_importances_
})

feature_importance = feature_importance.sort_values(
    by='Importance',
    ascending=False
)

plt.figure(figsize=(10,6))

sns.barplot(
    x='Importance',
    y='Feature',
    data=feature_importance.head(10)
)

plt.title('Feature Importance - XGBoost')

plt.show()

"""#PHASE 4: Model Evaluation and comparison


> MEMBER : Joud


"""

# Model Evaluation and Comparison


from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

class_names = ['Slight Injury', 'Serious Injury', 'Fatal Injury']

models_predictions = {
    'Logistic Regression': y_pred_lr,
    'SVM': y_pred_svm,
    'Random Forest': y_pred_rf,
    'XGBoost': y_pred_xgb
}

accuracy_results = []

for model_name, y_pred in models_predictions.items():
    print("=" * 50)
    print(model_name)

    acc = accuracy_score(y_test, y_pred)
    accuracy_results.append({
        'Model': model_name,
        'Accuracy': acc
    })


    print("Accuracy:", acc)
    print("\nClassification Report:")
    print(classification_report(y_test, y_pred, target_names=class_names))

    cm = confusion_matrix(y_test, y_pred)

    plt.figure(figsize=(7,5))

    sns.heatmap(
        cm,
        annot=True,
        fmt='d',
        cmap='Blues',
        xticklabels=class_names,
        yticklabels=class_names
    )
    plt.title(f'Confusion Matrix - {model_name}')
    plt.xlabel('Predicted')
    plt.ylabel('Actual')
    plt.show()

# Accuracy Comparison Table

results = pd.DataFrame(accuracy_results)

results_sorted = results.sort_values(by='Accuracy', ascending=False)

results_sorted

# Accuracy Comparison Chart

plt.figure(figsize=(8,4))

sns.barplot(
    x='Model',
    y='Accuracy',
    data=results_sorted
)

plt.title('Model Accuracy Comparison')
plt.xlabel('Machine Learning Model')
plt.ylabel('Accuracy')
plt.ylim(0, 1)
plt.xticks(rotation=20)
plt.show()

# Best Model Selection

best_model = results_sorted.iloc[0]

print("Best Model")
print("Model:", best_model['Model'])
print("Accuracy:", best_model['Accuracy'])